### ISSUE TITLE
Suggestion: improve the installation info

### ISSUE THREAD

**Issue by MAC-GH** [david-cortes/R-openblas-in-windows#2]
Hello,

Thank you for this clear installation guide.

Since one has already to fiddle with the R's installation for all this to work, for proper configuration I'd rather add the line:

OPENBLAS_NUM_THREADS=16

to etc/Renviron.site (the file has to be created as it doesn't exist in the standard R installation).

This method has the added benefit of making the R installation fully portable as is, does not require any user of a shared machine to perform the variable environment setup and does neither require a reboot afterwards.

Kind regards,
Mac

PS. I know it would have been easier if I had submitted a PR but unfortunately I'm not yet at that stage in my GitHub usage...

**Comment by andresuriane** [comment]
Dear Mac,

I tested your suggestion in R version 4.4.0. The file is now etc/Rcmd_environ (old etc/Renviron.site).
But it didn't work, see the tests below:


no modifications
> system.time({ x <- matrix(rnorm(5e3*5e3),5e3,5e3); tcrossprod(x) })
  usuário   sistema decorrido
    37.45      0.21     38.27


change the Rblas.dll and Rlapack.dll  with the line OPENBLAS_NUM_THREADS=16 in Rcmd_environ 
> system.time({ x <- matrix(rnorm(5e3*5e3),5e3,5e3); tcrossprod(x) })
  usuário   sistema decorrido
    10.54      1.40      2.06

change the Rblas.dll and Rlapack.dll  and remove line OPENBLAS_NUM_THREADS=16 in Rcmd_environ 
> system.time({ x <- matrix(rnorm(5e3*5e3),5e3,5e3); tcrossprod(x) })
  usuário   sistema decorrido
    10.36      1.22      1.93


The system automatically identifies the number of threads
If you have any idea why it didn't work I'd like to try your suggestion, because it's very simple.

**Comment by david-cortes** [comment]
Thanks for the suggesion. Did some testing however and my conclussion likewise is that it doesn't actually work if you use `etc/.Renviron`.

The environment variables would be set in the system as confirmed by `Sys.getenv`, but they need to be set **before** R is started, otherwise they have no effect.

Hence, setting them in an Renviron file does not result in OpenBLAS picking those values, while setting them through the control panel has the desired effect.

**Comment by MAC-GH** [comment]
Hello,

Not sure how your system is set up but it works nicely on mine. My CPU has only 8 cores and setting OPENBLAS_NUM_THREADS=8 in either Rcmd_environ or Renviron.site (not to be confused with .Renviron) or not setting it at all yield the same results. I'm using an up to date Windows 11, R v4.4.0, v4.3.3 and v4.2.3, the latest version of RStudio IDE and the latest version of OpenBLAS (v0.3.27). Please see below my results.
[tests_openblas.txt](https://github.com/david-cortes/R-openblas-in-windows/files/15268496/tests_openblas.txt)

I might add that I prefer my own Renviron.site instead of the R's bundled Rcmd_environ: in case of an R version upgrade via installr::updateR() if one chooses to uninstall the old version, if I recall correctly, the old Rcmd_environ would be removed but my own Renviron.site would be not and that serves as reminder that I have personal settings that should be added/updated (I think the newer versions of installr are smart enough and offer to copy all the setting files) in the new R version.

Kind regards,
Mac

PS: After more fiddling with the settings it seems that plain R (Rgui.exe) has some sort of cache it uses for its settings: while changing OPENBLAS_NUM_THREADS to 4 in either Rcmd_environ or Rprofile.site or not setting it at all, I keep getting Sys.getenv("OPENBLAS_NUM_THREADS") == 8. The RStudio IDE does not have this issue.

**Comment by andresuriane** [comment]
hey,

I don't know which version for sure, or if it was Windows 11, but now I'm seeing that using Windows 11 and starting from version 4.2.2 of R, the only modification necessary for R to properly use openblas was to replace the files Rblas.dll / Rlapack.dll.
I use ALMA Linux too, and in this system it is not necessary to modify the dll, just the number of threads, but even with ALMA starting from version 4.2.2, the identification of the number of threads was automatic. I didn't change the instructions because I didn't have time to identify which version this modification occurred.

Unfortunately, every update requires modification of the dll.


best regards,
Andre Suriane

**Comment by david-cortes** [comment]
From some testing, it does seem to be the case that if no thread-controlling env. var is set, it will default to the maximum number of threads on windows.

I'm also guesssing that the behavior you were seeing was that it started without the env. variable so it defaulted to the maximum number of threads, and then the env. variable was set to the same number of threads, giving the impression that it was controlling them.

If you were to set for example `OPENBLAS_NUM_THREADS=3` in the `Rcmd_environ` file, would that actually result in matrix operations using 3 threads?

**Comment by SCHansmann** [comment]
Hi, I'm not sure how to best get in touch so I thought I'd give it a shot here: I followed the installation guide, yet R does not detect the openblas dll (matrix products are still default and the benchmark crashes my R session)
Thanks for the help!

**Comment by david-cortes** [comment]
> Hi, I'm not sure how to best get in touch so I thought I'd give it a shot here: I followed the installation guide, yet R does not detect the openblas dll (matrix products are still default and the benchmark crashes my R session) Thanks for the help!

How did you verify that R wasn't using OpenBLAS? Does the location where you put the .dll files match with what you get from `.libPaths()` and `sessionInfo()`?

**Comment by SCHansmann** [comment]
Sorry for the late response!
Removing the environment functions provided in the installation and testing with benchmarks it appears openblas is being used after installation. Yet I still cannot get it to run with multiple threads. Doing this consistently crashes the R session. (Tested on ryzen 3975WX Pro and separate 7950x system. Even when setting lower numbers than detected by parallel::detectCores() the system seems to be unstable.

Thanks in advance!!

**Comment by david-cortes** [comment]
> Sorry for the late response! Removing the environment functions provided in the installation and testing with benchmarks it appears openblas is being used after installation. Yet I still cannot get it to run with multiple threads. Doing this consistently crashes the R session. (Tested on ryzen 3975WX Pro and separate 7950x system. Even when setting lower numbers than detected by parallel::detectCores() the system seems to be unstable.
> 
> Thanks in advance!!

No idea. You might want to ask at the OpenBLAS github page instead.
